### ISSUE TITLE
Async Peewee example is no longer suported?

### ISSUE THREAD

**Issue by drgarcia1986** [klen/muffin-example#1]
I try to make something like [1]:

``` python
@app.register('/db-async')
def db_async(request):
    results = yield from app.peewee.query(Test.select())
    return [t.data for t in results]
```

But I received an error `AttributeError: 'Application' object has no attribute 'peewee'`
If try with `app.ps.peewee.query()` I received error `AttributeError: 'Plugin' object has no attribute 'query'`

Is there any way to run queries async?

[1] https://github.com/klen/muffin-example/blob/master/example/views.py#L118-121

**Comment by klen** [comment]
Yes, I've removed the functionality from muffin-peewee. But Muffin-Peewee still manages connections to db asynchronously. Actually for now if you are going to run long time queries, you should use threadpool executor by your self.

However you can use aiopg/peewee-async libraries, but 
- It works slower than Muffin-Peewee with fast queries;
- You cannot use transactions;
- It produces a lot of connections errors  when there is a high concurency level

**Comment by drgarcia1986** [comment]
Ok, thank you :+1:
